### ISSUE TITLE
ADO.NET Factory 

### ISSUE THREAD

**Issue by bnayae** [outsidenote/eventualize#2]
Using [ADO.NET Factory](https://learn.microsoft.com/en-us/dotnet/framework/data/adonet/obtaining-a-dbproviderfactory) can abstract most OLTP providers

- SQLServerStorageAdapter : IStorageAdapter

**Comment by outsidenote** [comment]
Just for the record:
We agreed to examine this once we'd like to add a new relational storage adapter.

**Comment by bnaya-payoneer** [comment]
https://gist.github.com/fabianosobreira/7252168878920929431e503ab8c11f26
