### ISSUE TITLE
Scenario of End 2 End testing

### ISSUE THREAD

**Issue by bnaya-payoneer** [outsidenote/eventualize#56]
- Produce & Consume on the same request
- Produce on one request and Consume on another
- Produce on request and continuity Consume via a worker

* Review the efficiency on each scenario

**Comment by outsidenote** [comment]
Like we talked about in our e-meet:
All these scenarios should be tested using a single test case of 2 Aggregate instances created from the same Stream (one that writes and one that reads the Stream immediately afterwards).
